/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgeRatio: typeof import('./src/components/echarts/AgeRatio.vue')['default']
    BaseTemplate: typeof import('./src/components/echarts/BaseTemplate.vue')['default']
    ChinaMap: typeof import('./src/components/echarts/ChinaMap.vue')['default']
    CourseType: typeof import('./src/components/echarts/CourseType.vue')['default']
    DonatedChildren: typeof import('./src/components/echarts/DonatedChildren.vue')['default']
    DonationAmount: typeof import('./src/components/echarts/DonationAmount.vue')['default']
    DonationCount: typeof import('./src/components/echarts/DonationCount.vue')['default']
    DonationTrend: typeof import('./src/components/echarts/DonationTrend.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GeoDistribution: typeof import('./src/components/echarts/GeoDistribution.vue')['default']
    GoodsCategory: typeof import('./src/components/echarts/GoodsCategory.vue')['default']
    MenuBar: typeof import('./src/components/menu/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SexRatio: typeof import('./src/components/echarts/SexRatio.vue')['default']
    UsePeriod: typeof import('./src/components/echarts/UsePeriod.vue')['default']
    UserCount: typeof import('./src/components/echarts/UserCount.vue')['default']
    VisitRecord: typeof import('./src/components/echarts/VisitRecord.vue')['default']
  }
}
